### ISSUE TITLE
Break requirement for credentials job in tile

### ISSUE THREAD

**Issue by johnsonj** [cloudfoundry-community/stackdriver-tools#88]
# Background

The tile is an easy way for PCF users to deploy the nozzle. With a tile uploaded, it's possible to deploy the  agents (google-fluentd, stackdriver-agent) as addons:

```yaml
- name: stackdriver-tools
  version: latest 

addons:
- name: stackdriver-agents
  jobs:
  - name: credentials
    release: stackdriver-tools
  - name: google-fluentd
    release: stackdriver-tools
  - name: stackdriver-agent
    release: stackdriver-tools
  properties:
    credentials:
      application_default_credentials: |
        ...
    project_id: ...
```

# Problem

With this addon co-located we can no longer deploy the nozzle because it also deploys the credentials job.

## Error
```
Director task 152
  Started preparing deployment > Preparing deployment. Failed: Colocated job 'credentials' is already added to the instance group 'stackdriver-nozzle'. (00:00:00)

Error 100: Colocated job 'credentials' is already added to the instance group 'stackdriver-nozzle'.

Task 152 error
```

# Proposal

Allow the user to pass in service account JSON and use this by for the tile. Create a credentials file as part of the stackdriver-nozzle job and export [GOOGLE_APPLICATION_CREDENTIALS](https://developers.google.com/identity/protocols/application-default-credentials)
